build:
	@rm -rf ./src
	@rm -rf ./classes
	@rm -rf ./threads.jar
	cp -r /home/nico/NetBeansProjects/Threads/src .
	cp -r /home/nico/NetBeansProjects/Threads/build/classes .
	jar cvfm threads.jar manifest.txt -C classes .
